export const LOAD_REMINDER_SUCCESS = 'LOAD_REMINDER_SUCCESS';
export const LOAD_REMINDER_REQUEST = 'LOAD_REMINDER_REQUEST';

export const CREATE_NEW_REMINDER_SUCCESS = 'CREATE_NEW_REMINDER_SUCCESS';

